# Generated by Django 4.0.7 on 2023-07-20 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_squad_count', models.IntegerField(default=0)),
                ('min_squad_points', models.IntegerField(default=0)),
                ('max_squad_count', models.IntegerField(default=0)),
                ('max_squad_points', models.IntegerField(default=0)),
                ('special', models.CharField(max_length=250)),
                ('has_grenade_or_C4', models.BooleanField(default=False)),
                ('has_bazooka_or_flamethrower', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Infantry Models',
            },
        ),
        migrations.CreateModel(
            name='Infantry_Upgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upgrade_points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Infantry Upgrades',
            },
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('firing_range', models.IntegerField(default=0)),
                ('min_attack_count', models.IntegerField(default=0)),
                ('max_attack_count', models.IntegerField(default=0)),
                ('doubles_vs_vehicle', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Weapons',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Upgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transport_bonus', models.IntegerField(default=0)),
                ('armor_bonus', models.IntegerField(default=0)),
                ('upgrade_points', models.IntegerField(default=0)),
                ('weapon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.weapons')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Upgrades',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('armor_bonus', models.IntegerField(default=0)),
                ('special', models.CharField(max_length=250)),
                ('unit_count', models.IntegerField(default=0)),
                ('unit_points', models.IntegerField(default=0)),
                ('weapon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.weapons')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Models',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.user')),
            ],
            options={
                'verbose_name_plural': 'Army Lists',
            },
        ),
        migrations.CreateModel(
            name='j_vehicle_upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.vehicle')),
                ('vehicle_upgrade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.vehicle_upgrades')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Upgrades',
            },
        ),
        migrations.CreateModel(
            name='j_user_list_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.lists')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.user')),
            ],
            options={
                'verbose_name_plural': 'List Ratings',
            },
        ),
        migrations.CreateModel(
            name='j_user_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.lists')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.user')),
            ],
            options={
                'verbose_name_plural': 'User Lists',
            },
        ),
        migrations.CreateModel(
            name='j_list_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infantry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.infantry')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.lists')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.vehicle')),
            ],
            options={
                'verbose_name_plural': 'List Entries',
            },
        ),
        migrations.CreateModel(
            name='j_infantry_upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infantry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.infantry')),
                ('infantry_upgrade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.infantry_upgrades')),
            ],
            options={
                'verbose_name_plural': 'Infantry Upgrades',
            },
        ),
        migrations.AddField(
            model_name='infantry_upgrades',
            name='weapon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.weapons'),
        ),
        migrations.AddField(
            model_name='infantry',
            name='weapon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armymencombat.weapons'),
        ),
    ]
