# Generated by Django 4.0.7 on 2023-07-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armymencombat', '0002_rename_user_users_alter_j_user_list_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='j_infantry_upgrade',
            options={'verbose_name_plural': 'Join: Infantry Upgrades Taken'},
        ),
        migrations.AlterModelOptions(
            name='j_list_entry',
            options={'verbose_name_plural': 'Join: List Entries'},
        ),
        migrations.AlterModelOptions(
            name='j_user_list',
            options={'verbose_name_plural': 'Join: User Lists'},
        ),
        migrations.AlterModelOptions(
            name='j_user_list_rating',
            options={'verbose_name_plural': 'Join: List Ratings'},
        ),
        migrations.AlterModelOptions(
            name='j_vehicle_upgrade',
            options={'verbose_name_plural': 'Join: Vehicle Upgrades Taken'},
        ),
    ]
