# Generated by Django 4.0.7 on 2023-07-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armymencombat', '0003_alter_j_infantry_upgrade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='j_list_entry',
            options={'verbose_name_plural': 'Join: Army List Entries'},
        ),
        migrations.AlterModelOptions(
            name='j_user_list',
            options={'verbose_name_plural': 'Join: User Army Lists'},
        ),
        migrations.AlterModelOptions(
            name='j_user_list_rating',
            options={'verbose_name_plural': 'Join: User Army List Ratings'},
        ),
    ]
