# Generated by Django 4.0.7 on 2023-07-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armymencombat', '0004_alter_j_list_entry_options_alter_j_user_list_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infantry',
            name='has_bazooka_or_flamethrower',
        ),
        migrations.RemoveField(
            model_name='infantry',
            name='has_grenade_or_C4',
        ),
    ]
