# Generated by Django 4.0.7 on 2023-07-21 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armymencombat', '0005_remove_infantry_has_bazooka_or_flamethrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='weapon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armymencombat.weapons'),
        ),
    ]
