# Generated by Django 4.0.7 on 2023-07-21 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armymencombat', '0006_alter_vehicle_weapon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_upgrades',
            name='weapon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armymencombat.weapons'),
        ),
    ]
