# Generated by Django 4.0.7 on 2023-07-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armymencombat', '0008_rule_types_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='rule_type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Rule_Types',
        ),
    ]
