# Generated by Django 4.0.7 on 2023-07-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armymencombat', '0009_alter_rules_rule_type_delete_rule_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='rule_text',
            field=models.TextField(max_length=500),
        ),
    ]
